<?php
include "./api.php";

$sql = "CREATE TABLE root(
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(30) NOT NULL,
  type VARCHAR(30) NOT NULL,
  parent INT DEFAULT -1,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)";

$result = requset($sql);